[pytest]
filterwarnings =
    ignore:Support for class-based `config` is deprecated:pydantic.warnings.PydanticDeprecatedSince20:core\.config
    ignore:Support for class-based `config` is deprecated:pydantic.warnings.PydanticDeprecatedSince20:schemas\.users
    ignore:datetime\.datetime\.utcnow\(\) is deprecated:DeprecationWarning:sqlalchemy\.sql\.schema
    ignore:datetime\.datetime\.utcnow\(\) is deprecated:DeprecationWarning:core\.security
